#!/bin/bash

#SBATCH --job-name=fourcast
#SBATCH --partition=plgrid-gpu-a100
#SBATCH --time=00:30:00
#SBATCH --account=plgimgwprzybycien-gpu-a100
#xxx SBATCH --cpus-per-task=4
#SBATCH --mem=108G
#SBATCH -N 1
#SBATCH --gres=gpu
#SBATCH --output=/net/tscratch/people/plgorhid/fourcast-output/fourcast-slurm.out
#SBATCH --error=/net/tscratch/people/plgorhid/fourcast-output/fourcast-slurm.err

module load Python

# pip install numpy
# pip install h5py
# pip install torch
# pip install torchvision
# pip install matplotlib
# pip install wandb
# pip install ruamel.yaml
# pip install timm
# pip install einops

cd $PLG_GROUPS_STORAGE/plggorheuro/fourcast/src
python stochastic_inference.py \
       --yaml_config '/net/pr2/projects/plgrid/plggorheuro/fourcast/src/config/AFNO.yaml' \
       --config=afno_backbone \
       --n_pert 2 \
       --data_path '/net/pr2/projects/plgrid/plggorheuro/fourcast/data/2018.h5' \
       --weights '/net/pr2/projects/plgrid/plggorheuro/fourcast/model-weights/backbone.ckpt' \
       --override_dir '/net/pr2/projects/plgrid/plggorheuro/fourcast/bounce/' 
